appDefault:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation


appCategory:
    resource: "@AppBundle/Controller/CategoryController.php"
    type:     annotation
    prefix : /{_locale}/
    requirements:
        _locale: es|en

appPerson:
    resource: "@AppBundle/Controller/PersonController.php"
    type:     annotation
    prefix : /{_locale}/
    requirements:
        _locale: es|en

appProduct:
    resource: "@AppBundle/Controller/ProductController.php"
    type:     annotation
    prefix : /{_locale}/
    requirements:
        _locale: es|en


appCircuit:
    resource: "@AppBundle/Controller/CircuitController.php"
    type:     annotation
    prefix : /{_locale}/
    requirements:
        _locale: es|en

appCarrera:
    resource: "@AppBundle/Controller/CarreraController.php"
    type:     annotation
    prefix : /{_locale}/
    requirements:
        _locale: es|en

appPosition:
    resource: "@AppBundle/Controller/PositionController.php"
    type:     annotation
    prefix : /{_locale}/
    requirements:
        _locale: es|en

T43:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /T43

T44:
    resource: "@AppBundle/Resources/config/T44/routing.yml"
    prefix: /T44

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix : /{_locale}/
    requirements:
        _locale: es|en

contact:
    path:     /{_locale}/product/list/jjjjjjj
    defaults: { _controller: AppBundle:Product:list }
    requirements:
        _locale: es|en
